### ISSUE TITLE
Failing to start in local mode

### ISSUE THREAD

**Issue by pegasia** [kpollich/piltovergg#6]
```
C:\Users\Mikk\Desktop\piltovergg>npm start

> piltovergg-server@0.0.0 start C:\Users\Mikk\Desktop\piltovergg
> concurrently "npm run server" "npm run client"

[1]
[1] > piltovergg-server@0.0.0 client C:\Users\Mikk\Desktop\piltovergg
[1] > cd client && npm start
[1]
[0]
[0] > piltovergg-server@0.0.0 server C:\Users\Mikk\Desktop\piltovergg
[0] > node server.js
[0]
[0] C:\Users\Mikk\Desktop\piltovergg\server.js:30
[0] app.get('/api/summoners/:region/:name', async (request, response) => {
[0]                                               ^
[0] SyntaxError: Unexpected token (
[0]     at createScript (vm.js:56:10)
[0]     at Object.runInThisContext (vm.js:97:10)
[0]     at Module._compile (module.js:542:28)
[0]     at Object.Module._extensions..js (module.js:579:10)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.runMain (module.js:604:10)
[0]     at run (bootstrap_node.js:390:7)
[0]     at startup (bootstrap_node.js:150:9)
[0]
[0] npm ERR! Windows_NT 10.0.10586
[0] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
[0] npm ERR! node v6.10.3
[0] npm ERR! npm  v3.10.10
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! piltovergg-server@0.0.0 server: `node server.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the piltovergg-server@0.0.0 server script 'node server.js'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the piltovergg-server package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     node server.js
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs piltovergg-server
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls piltovergg-server
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     C:\Users\Mikk\Desktop\piltovergg\npm-debug.log
[0] npm run server exited with code 1
[1]
[1] > piltovergg-client@0.1.0 start C:\Users\Mikk\Desktop\piltovergg\client
[1] > react-scripts start
[1]
[1] 'react-scripts' is not recognized as an internal or external command,
[1] operable program or batch file.
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.10586
[1] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
[1] npm ERR! node v6.10.3
[1] npm ERR! npm  v3.10.10
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! piltovergg-client@0.1.0 start: `react-scripts start`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the piltovergg-client@0.1.0 start script 'react-scripts start'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the piltovergg-client package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     react-scripts start
[1] npm ERR!
[1]  You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs piltovergg-client
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls piltovergg-client
[1] npm ERR! There is likely additional logging output above.
[1] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     C:\Users\Mikk\Desktop\piltovergg\client\npm-debug.log
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.10586
[1] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "client"
[1] npm ERR! node v6.10.3
[1] npm ERR! npm  v3.10.10
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! piltovergg-server@0.0.0 client: `cd client && npm start`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the piltovergg-server@0.0.0 client script 'cd client && npm start'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the piltovergg-server package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     cd client && npm start
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs piltovergg-server
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls piltovergg-server
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     C:\Users\Mikk\Desktop\piltovergg\npm-debug.log
[1] npm run client exited with code 1

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! piltovergg-server@0.0.0 start: `concurrently "npm run server" "npm run client"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the piltovergg-server@0.0.0 start script 'concurrently "npm run server" "npm run client"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the piltovergg-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run server" "npm run client"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs piltovergg-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls piltovergg-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mikk\Desktop\piltovergg\npm-debug.log
```

**Comment by kpollich** [comment]
This project requires Node 7.0+ for native `async/await` syntax. It's also a barely implemented pet project, so don't expect too much out of this 😄

**Comment by pegasia** [comment]
Hey, thanks for quick reply!
I will try to install node 7 now, and will keep you updated!

**Comment by pegasia** [comment]
Hi again, it seems to start up the server, but with some errors.
When i visit localhost:8000 im getting white page with text "Cannot GET /"
My console log; `C:\Users\Mikk\Desktop\piltovergg>docker-compose up -d
piltovergg_redis_1 is up-to-date

C:\Users\Mikk\Desktop\piltovergg>npm run start-dev

> piltovergg-server@0.0.0 start-dev C:\Users\Mikk\Desktop\piltovergg
> concurrently "nodemon server.js" "npm run client"

[1]
[1] > piltovergg-server@0.0.0 client C:\Users\Mikk\Desktop\piltovergg
[1] > cd client && npm start
[1]
[1]
[1] > piltovergg-client@0.1.0 start C:\Users\Mikk\Desktop\piltovergg\client
[1] > react-scripts start
[1]
[1] 'react-scripts' is not recognized as an internal or external command,
[1] operable program or batch file.
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.10586
[1] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
[1] npm ERR! node v7.7.4
[1] npm ERR! npm  v4.1.2
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! piltovergg-client@0.1.0 start: `react-scripts start`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the piltovergg-client@0.1.0 start script 'react-scripts start'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the piltovergg-client package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     react-scripts start
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs piltovergg-client
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls piltovergg-client
[1] npm ERR! There is likely additional logging output above.
[1] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     C:\Users\Mikk\Desktop\piltovergg\client\npm-debug.log
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.10586
[1] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "client"
[1] npm ERR! node v7.7.4
[1] npm ERR! npm  v4.1.2
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! piltovergg-server@0.0.0 client: `cd client && npm start`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the piltovergg-server@0.0.0 client script 'cd client && npm start'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the piltovergg-server package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     cd client && npm start
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs piltovergg-server
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls piltovergg-server
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     C:\Users\Mikk\Desktop\piltovergg\npm-debug.log
[1] npm run client exited with code 1
[0] [nodemon] 1.11.0
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node server.js`
[0] app running on port 8000
[0] GET / 404 3.753 ms - 139
[0] GET /favicon.ico 404 1.354 ms - 150`

**Comment by kpollich** [comment]
This looks like an issue with the `react-scripts` dependency coming from the `create-react-app` project (https://github.com/facebookincubator/create-react-app). Have you installed dependencies for the `client` project? 

```sh
$ cd client
$ yarn 
```

I'm sorry I don't have very good "up and running" docs for this project, since I never expected anyone else to try and run it 😄  - I can look more at this later and make sure running locally works consistently for everyone.

**Comment by pegasia** [comment]
Works now, huge thanks!
